export const data = {
  // test
  telangana: [
    {
      name: "Parlapally",
      pdf: "/Assets/telenaga/parlapally/pdf.pdf",
      profileImg: "/Assets/telenaga/parlapally/profile.webp",
      profileName: "Dr.Anupama",
      images: [
        "./Assets/telenaga/parlapally/img (1).webp",
        "./Assets/telenaga/parlapally/img (2).webp",
        "./Assets/telenaga/parlapally/img (3).webp",
        "./Assets/telenaga/parlapally/img (4).webp",
        "./Assets/telenaga/parlapally/img (5).webp",
      ],
    },
    {
      name: "Buddaram",
      pdf: "/Assets/telenaga/buddaram/pdf.pdf",
      profileImg: "/Assets/telenaga/buddaram/profile.webp",
      profileName: "Dr.Ambatpalli Sarojini Rao",
      images: [
        "./Assets/telenaga/buddaram/img (1).webp",
        "./Assets/telenaga/buddaram/img (3).webp",
        "./Assets/telenaga/buddaram/img (4).webp",
        "./Assets/telenaga/buddaram/img (5).webp",
      ],
    },
    {
      name: "Saloora",
      pdf: "/Assets/telenaga/saloora/pdf.pdf",
      profileImg: "/Assets/telenaga/saloora/profile.webp",
      profileName: "Dr Ravinder Reddy Kandula",
      images: [
        "./Assets/telenaga/saloora/img (1).webp",
        "./Assets/telenaga/saloora/img (2).webp",
        "./Assets/telenaga/saloora/img (3).webp",
        "./Assets/telenaga/saloora/img (4).webp",
        "./Assets/telenaga/saloora/img (5).webp",
      ],
    },
    {
      name: "Peddapuram",
      pdf: "/Assets/telenaga/Peddapur/pdf.pdf",
      profileImg: "/Assets/telenaga/Peddapur/profile.webp",
      profileName: "Dr Geeta Reddy Lekkala",
      images: [
        "./Assets/telenaga/Peddapur/img (1).webp",
        "./Assets/telenaga/Peddapur/img (2).webp",
        "./Assets/telenaga/Peddapur/img (3).webp",
        "./Assets/telenaga/Peddapur/img (4).webp",
        "./Assets/telenaga/Peddapur/img (5).webp",
      ],
    },
    {
      name: "Bairanpally",
      pdf: "/Assets/telenaga/Bairanpally/pdf.pdf",
      profileImg: "/Assets/telenaga/Bairanpally/profile.webp",
      profileName: "Dr Sunita Reddy",
      images: [
        "./Assets/telenaga/Bairanpally/img (1).webp",
        "./Assets/telenaga/Bairanpally/img (2).webp",
        "./Assets/telenaga/Bairanpally/img (3).webp",
        "./Assets/telenaga/Bairanpally/img (4).webp",
        "./Assets/telenaga/Bairanpally/img (5).webp",
      ],
    },
    {
      name: "Birkoor",
      pdf: "/Assets/telenaga/Birkoor/pdf.pdf",
      profileImg: "/Assets/telenaga/Birkoor/profile.webp",
      profileName: "Dr Sunil Kaza",
      images: [
        "./Assets/telenaga/Birkoor/img (1).webp",
        "./Assets/telenaga/Birkoor/img (2).webp",
        "./Assets/telenaga/Birkoor/img (3).webp",
        "./Assets/telenaga/Birkoor/img (4).webp",
        "./Assets/telenaga/Birkoor/img (5).webp",
      ],
    },
    {
      name: "Gowlipura",
      pdf: "/Assets/telenaga/Gowlipura/pdf.pdf",
      profileImg: "/Assets/telenaga/Gowlipura/profile.webp",
      profileName: "Dr. Swatantra Mitta and Dr. Srinivas Mitta",
      images: [
        "./Assets/telenaga/Gowlipura/img (1).webp",
        "./Assets/telenaga/Gowlipura/img (2).webp",
        "./Assets/telenaga/Gowlipura/img (3).webp",
        "./Assets/telenaga/Gowlipura/img (4).webp",
        "./Assets/telenaga/Gowlipura/img (5).webp",
      ],
    },
    {
      name: "Devarappula",
      pdf: "/Assets/telenaga/Devarappula/pdf.pdf",
      profileImg: "/Assets/telenaga/Devarappula/profile.webp",
      profileName: "Dr. Sujeeth Punnam",
      images: [
        "./Assets/telenaga/Devarappula/img (1).webp",
        "./Assets/telenaga/Devarappula/img (2).webp",
        "./Assets/telenaga/Devarappula/img (3).webp",
        "./Assets/telenaga/Devarappula/img (4).webp",
        "./Assets/telenaga/Devarappula/img (5).webp",
      ],
    },
    {
      name: "Mulkanoor",
      pdf: "/Assets/telenaga/Mulkanoor/pdf.pdf",
      profileImg: "/Assets/telenaga/Mulkanoor/profile.webp",
      profileName: "Dr Hyma kandhula",
      images: [
        "./Assets/telenaga/Mulkanoor/img (1).webp",
        "./Assets/telenaga/Mulkanoor/img (2).webp",
        "./Assets/telenaga/Mulkanoor/img (3).webp",
        "./Assets/telenaga/Mulkanoor/img (4).webp",
        "./Assets/telenaga/Mulkanoor/img (5).webp",
      ],
    },
    {
      name: "Wadkapur",
      pdf: "/Assets/telenaga/Wadkapur/pdf.pdf",
      profileImg: "/Assets/telenaga/Wadkapur/profile.webp",
      profileName: "Dr. Pulluru Sreedhar Rao",
      images: [
        "./Assets/telenaga/Wadkapur/img (1).webp",
        "./Assets/telenaga/Wadkapur/img (2).webp",
        "./Assets/telenaga/Wadkapur/img (3).webp",
        "./Assets/telenaga/Wadkapur/img (4).webp",
        "./Assets/telenaga/Wadkapur/img (5).webp",
      ],
    },
    {
      name: "Tiryani",
      pdf: "/Assets/telenaga/Tiryani/pdf.pdf",
      profileImg: "/Assets/telenaga/Tiryani/profile.webp",
      profileName: "Dr Uma Eleti",
      images: [
        "./Assets/telenaga/Tiryani/img (1).webp",
        "./Assets/telenaga/Tiryani/img (2).webp",
        "./Assets/telenaga/Tiryani/img (3).webp",
        "./Assets/telenaga/Tiryani/img (4).webp",
        "./Assets/telenaga/Tiryani/img (5).webp",
      ],
    },
    {
      name: "Ramaipally",
      pdf: "/Assets/telenaga/Ramaipally/pdf.pdf",
      profileImg: "/Assets/telenaga/Ramaipally/profile.webp",
      profileName: "Dr Satheesh Kathula",
      images: [
        "./Assets/telenaga/Ramaipally/img (1).webp",
        "./Assets/telenaga/Ramaipally/img (2).webp",
        "./Assets/telenaga/Ramaipally/img (3).webp",
        "./Assets/telenaga/Ramaipally/img (4).webp",
        "./Assets/telenaga/Ramaipally/img (5).webp",
      ],
    },
    {
      name: "Mittapally",
      pdf: "/Assets/telenaga/Mittapally/pdf.pdf",
      profileImg: "/Assets/telenaga/Mittapally/profile.webp",
      profileName: "Dr. Daram Hanumanth Reddy",
      images: [
        "./Assets/telenaga/Mittapally/img (1).webp",
        "./Assets/telenaga/Mittapally/img (2).webp",
        "./Assets/telenaga/Mittapally/img (3).webp",
        "./Assets/telenaga/Mittapally/img (4).webp",
        "./Assets/telenaga/Mittapally/img (5).webp",
      ],
    },
    {
      name: "Dwarakapet",
      pdf: "/Assets/telenaga/Dwarakapet/pdf.pdf",
      profileImg: "/Assets/telenaga/Dwarakapet/profile.webp",
      profileName: "Dr. Suresh Reddy ",
      images: [
        "./Assets/telenaga/Dwarakapet/img (1).webp",
        "./Assets/telenaga/Dwarakapet/img (2).webp",
        "./Assets/telenaga/Dwarakapet/img (3).webp",
      ],
    },
  ],
  gujrat: [
    {
      name: "Khakhrechi",
      pdf: "/Assets/gujrat/Khakhrechi/pdf.pdf",
      profileImg: "/Assets/gujrat/Khakhrechi/profile.webp",
      profileName: "Dr Yagnesh Raval",
      images: [
        "./Assets/gujrat/Khakhrechi/img (1).webp",
        "./Assets/gujrat/Khakhrechi/img (2).webp",
        "./Assets/gujrat/Khakhrechi/img (3).webp",
        "./Assets/gujrat/Khakhrechi/img (4).webp",
        "./Assets/gujrat/Khakhrechi/img (5).webp",
      ],
    },
    {
      name: "Gheti",
      pdf: "/Assets/gujrat/Gheti/pdf.pdf",
      profileImg: "/Assets/gujrat/Gheti/profile.webp",
      profileName: "Dr. Nikhil Bayani",
      images: [
        "./Assets/gujrat/Gheti/img (1).webp",
        "./Assets/gujrat/Gheti/img (2).webp",
        "./Assets/gujrat/Gheti/img (3).webp",
        "./Assets/gujrat/Gheti/img (4).webp",
        "./Assets/gujrat/Gheti/img (5).webp",
      ],
    },
    {
      name: "Sanjanasar",
      pdf: "/Assets/gujrat/Sanjanasar/pdf.pdf",
      profileImg: "/Assets/gujrat/Sanjanasar/profile.webp",
      profileName: "Dr Ramesh R karia",
      images: [
        "./Assets/gujrat/Sanjanasar/img (1).webp",
        "./Assets/gujrat/Sanjanasar/img (2).webp",
        "./Assets/gujrat/Sanjanasar/img (3).webp",
        "./Assets/gujrat/Sanjanasar/img (4).webp",
        "./Assets/gujrat/Sanjanasar/img (5).webp",
      ],
    },
    {
      name: "Jambughoda",
      pdf: "/Assets/gujrat/Jambughoda/pdf.pdf",
      profileImg: "/Assets/gujrat/Jambughoda/profile.webp",
      profileName: "Dr Jayesh Shah",
      images: [
        "./Assets/gujrat/Jambughoda/img (1).webp",
        "./Assets/gujrat/Jambughoda/img (2).webp",
        "./Assets/gujrat/Jambughoda/img (3).webp",
        "./Assets/gujrat/Jambughoda/img (4).webp",
        "./Assets/gujrat/Jambughoda/img (5).webp",
      ],
    },
    {
      name: "Bilimora",
      pdf: "/Assets/gujrat/Bilimora/pdf.pdf",
      profileImg: "/Assets/gujrat/Bilimora/profile.webp",
      profileName: "Dr Sumul Raval",
      images: [
        "./Assets/gujrat/Bilimora/img (1).webp",
        "./Assets/gujrat/Bilimora/img (2).webp",
        "./Assets/gujrat/Bilimora/img (3).webp",
        "./Assets/gujrat/Bilimora/img (4).webp",
        "./Assets/gujrat/Bilimora/img (5).webp",
      ],
    },
    {
      name: "Hansot",
      pdf: "/Assets/gujrat/Hansot/pdf.pdf",
      profileImg: "/Assets/gujrat/Hansot/profile.webp",
      profileName: "Dr Nirav Parik",
      images: [
        "./Assets/gujrat/Hansot/img (1).webp",
        "./Assets/gujrat/Hansot/img (2).webp",
        "./Assets/gujrat/Hansot/img (3).webp",
        "./Assets/gujrat/Hansot/img (4).webp",
        "./Assets/gujrat/Hansot/img (5).webp",
      ],
    },
    {
      name: "Ambaliyara",
      pdf: "/Assets/gujrat/Ambaliyara/pdf.pdf",
      profileImg: "/Assets/gujrat/Ambaliyara/profile.webp",
      profileName: "Dr Prakash Patel",
      images: [
        "./Assets/gujrat/Ambaliyara/img (1).webp",
        "./Assets/gujrat/Ambaliyara/img (2).webp",
        "./Assets/gujrat/Ambaliyara/img (3).webp",
        "./Assets/gujrat/Ambaliyara/img (4).webp",
        "./Assets/gujrat/Ambaliyara/img (5).webp",
      ],
    },
    {
      name: "Undavi",
      pdf: "/Assets/gujrat/Undavi/pdf.pdf",
      profileImg: "/Assets/karnataka/kesaramadu/profile.webp",
      profileName: "Anoop & Amita Mamtani",
      images: [
        "./Assets/gujrat/Undavi/img (1).webp",
        "./Assets/gujrat/Undavi/img (2).webp",
        "./Assets/gujrat/Undavi/img (3).webp",
        "./Assets/gujrat/Undavi/img (4).webp",
        "./Assets/gujrat/Undavi/img (5).webp",
      ],
    },
    {
      name: "Dhuljipura",
      pdf: "/Assets/gujrat/Dhuljipura/pdf.pdf",
      profileImg: "/Assets/karnataka/kesaramadu/profile.webp",
      profileName: "Anoop & Amita Mamtani",
      images: [
        "./Assets/gujrat/Dhuljipura/img (1).webp",
        "./Assets/gujrat/Dhuljipura/img (2).webp",
        "./Assets/gujrat/Dhuljipura/img (3).webp",
        "./Assets/gujrat/Dhuljipura/img (4).webp",
        "./Assets/gujrat/Dhuljipura/img (5).webp",
      ],
    },
    {
      name: "Dadiyapura",
      pdf: "/Assets/telenaga/buddaram/pdf.pdf",
      profileImg: "/Assets/karnataka/kesaramadu/profile.webp",
      profileName: "Anoop & Amita Mamtani",
      images: [
        "./Assets/gujrat/Dadiyapura/img (1).webp",
        "./Assets/gujrat/Dadiyapura/img (2).webp",
        "./Assets/gujrat/Dadiyapura/img (3).webp",
        "./Assets/gujrat/Dadiyapura/img (4).webp",
        "./Assets/gujrat/Dadiyapura/img (5).webp",
        "./Assets/gujrat/Dadiyapura/img (6).webp",
        "./Assets/gujrat/Dadiyapura/img (7).webp",
        "./Assets/gujrat/Dadiyapura/img (8).webp",
        "./Assets/gujrat/Dadiyapura/img (9).webp",
        "./Assets/gujrat/Dadiyapura/img (10).webp",
        "./Assets/gujrat/Dadiyapura/img (11).webp",
        "./Assets/gujrat/Dadiyapura/img (12).webp",
      ],
    },
    {
      name: "Jalalpur",
      pdf: "/Assets/gujrat/Jalalpur/pdf.pdf",
      profileImg: "/Assets/karnataka/kesaramadu/profile.webp",
      profileName: "Anoop & Amita Mamtani",
      images: [
        "./Assets/gujrat/Jalalpur/img (1).webp",
        "./Assets/gujrat/Jalalpur/img (2).webp",
        "./Assets/gujrat/Jalalpur/img (3).webp",
        "./Assets/gujrat/Jalalpur/img (4).webp",
        "./Assets/gujrat/Jalalpur/img (5).webp",
      ],
    },
    {
      name: "Renoda",
      pdf: "/Assets/gujrat/Renoda/pdf.pdf",
      profileImg: "/Assets/karnataka/kesaramadu/profile.webp",
      profileName: "Anoop & Amita Mamtani",
      images: [
        "./Assets/gujrat/Renoda/img (1).webp",
        "./Assets/gujrat/Renoda/img (2).webp",
        "./Assets/gujrat/Renoda/img (3).webp",
        "./Assets/gujrat/Renoda/img (4).webp",
        "./Assets/gujrat/Renoda/img (5).webp",
      ],
    },
    {
      name: "Rajpur",
      pdf: "/Assets/gujrat/Rajpur/pdf.pdf",
      profileImg: "/Assets/karnataka/kesaramadu/profile.webp",
      profileName: "Anoop & Amita Mamtani",
      images: [
        "./Assets/gujrat/Rajpur/img (1).webp",
        "./Assets/gujrat/Rajpur/img (2).webp",
        "./Assets/gujrat/Rajpur/img (3).webp",
        "./Assets/gujrat/Rajpur/img (4).webp",
        "./Assets/gujrat/Rajpur/img (5).webp",
      ],
    },
  ],
  andhrapradesh: [
    {
      name: "Alikam",
      pdf: "./Assets/andhra/alikam/pdf.pdf",
      profileImg: "/Assets/andhra/alikam/profile.webp",
      profileName: "Dr Jagan Kakarala",
      images: [
        "./Assets/andhra/alikam/img (1).webp",
        "./Assets/andhra/alikam/img (2).webp",
        "./Assets/andhra/alikam/img (3).webp",
        "./Assets/andhra/alikam/img (4).webp",
        "./Assets/andhra/alikam/img (5).webp",
      ],
    },
    {
      name: "Yerraguntapally",
      pdf: "./Assets/andhra/Yerraguntapally/pdf.pdf",
      profileImg: "/Assets/andhra/Yerraguntapally/profile.webp",
      profileName: "Dr. Dhananjay Reddy",
      images: [
        "./Assets/andhra/Yerraguntapally/img (1).webp",
        "./Assets/andhra/Yerraguntapally/img (2).webp",
        "./Assets/andhra/Yerraguntapally/img (3).webp",
        "./Assets/andhra/Yerraguntapally/img (4).webp",
        "./Assets/andhra/Yerraguntapally/img (5).webp",
      ],
    },
    {
      name: "Royyuru",
      pdf: "./Assets/andhra/Royyuru/pdf.pdf",
      profileImg: "/Assets/andhra/Royyuru/profile.webp",
      profileName: "Dr.Rom Mohan Kopparthi",
      images: [
        "./Assets/andhra/Royyuru/img (1).webp",
        "./Assets/andhra/Royyuru/img (2).webp",
        "./Assets/andhra/Royyuru/img (3).webp",
        "./Assets/andhra/Royyuru/img (4).webp",
        "./Assets/andhra/Royyuru/img (5).webp",
      ],
    },
    {
      name: "Kundalapally",
      pdf: "./Assets/andhra/Kundalapally/img (19).webp",
      profileImg: "/Assets/andhra/Kundalapally/profile.webp",
      profileName: "Dr Radhika Akella",
      images: [
        "./Assets/andhra/Kundalapally/img (1).webp",
        "./Assets/andhra/Kundalapally/img (2).webp",
        "./Assets/andhra/Kundalapally/img (3).webp",
        "./Assets/andhra/Kundalapally/img (4).webp",
        "./Assets/andhra/Kundalapally/img (5).webp",
      ],
    },
    {
      name: "Thondavada",
      pdf: "./Assets/andhra/Thondavada/pdf.pdf",
      profileImg: "/Assets/andhra/Thondavada/profile.webp",
      profileName: "Dr. Mohan Mallam",
      images: [
        "./Assets/andhra/Thondavada/img (1).webp",
        "./Assets/andhra/Thondavada/img (2).webp",
        "./Assets/andhra/Thondavada/img (3).webp",
        "./Assets/andhra/Thondavada/img (4).webp",
        "./Assets/andhra/Thondavada/img (5).webp",
      ],
    },
    {
      name: "Ventrapragada",
      pdf: "./Assets/andhra/Ventrapragada/pdf.pdf",
      profileImg: "/Assets/andhra/Ventrapragada/profile.webp",
      profileName: "Dr. Movva",
      images: [
        "./Assets/andhra/Ventrapragada/img (1).webp",
        "./Assets/andhra/Ventrapragada/img (2).webp",
        "./Assets/andhra/Ventrapragada/img (3).webp",
        "./Assets/andhra/Ventrapragada/img (4).webp",
        "./Assets/andhra/Ventrapragada/img (5).webp",
      ],
    },
    {
      name: "Obulareddypalli",
      pdf: "./Assets/andhra/Obulareddypalli/pdf.pdf",
      profileImg: "/Assets/andhra/Obulareddypally/profile.webp",
      profileName: "Dr. Krishna Reddy Aruna Reddy",
      images: [
        "./Assets/andhra/Obulareddypalli/img (1).webp",
        "./Assets/andhra/Obulareddypalli/img (2).webp",
        "./Assets/andhra/Obulareddypalli/img (3).webp",
        "./Assets/andhra/Obulareddypalli/img (4).webp",
        "./Assets/andhra/Obulareddypalli/img (5).webp",
      ],
    },
    {
      name: "Obulareddypally Thanda",
      pdf: "./Assets/andhra/Obulareddypally/pdf.pdf",
      profileImg: "/Assets/andhra/Obulareddypally/profile.webp",
      profileName: "Dr. Krishna Reddy Aruna Reddy",
      images: [
        "./Assets/andhra/Obulareddypally Thanda/img (1).webp",
        "./Assets/andhra/Obulareddypally Thanda/img (2).webp",
        "./Assets/andhra/Obulareddypally Thanda/img (3).webp",
        "./Assets/andhra/Obulareddypally Thanda/img (4).webp",
        "./Assets/andhra/Obulareddypally Thanda/img (5).webp",
      ],
    },
    {
      name: "Pappulavaripalem",
      pdf: "./Assets/andhra/Pappula Vari/pdf.pdf",
      profileImg: "/Assets/andhra/Pappula Vari/profile.webp",
      profileName: "Dr Radha Ramana Murthy",
      images: [
        "./Assets/andhra/Pappula Vari/img (1).webp",
        "./Assets/andhra/Pappula Vari/img (2).webp",
        "./Assets/andhra/Pappula Vari/img (3).webp",
        "./Assets/andhra/Pappula Vari/img (4).webp",
        "./Assets/andhra/Pappula Vari/img (5).webp",
      ],
    },
    {
      name: "Pennabadivandlapally",
      pdf: "./Assets/andhra/PENNABADIVANDLAPALLY/pdf.pdf",
      profileImg: "/Assets/andhra/Obulareddypally/profile.webp",
      profileName: "Dr. Krishna Reddy Aruna Reddy",
      images: [
        "./Assets/andhra/PENNABADIVANDLAPALLY/img (1).webp",
        "./Assets/andhra/PENNABADIVANDLAPALLY/img (2).webp",
        "./Assets/andhra/PENNABADIVANDLAPALLY/img (3).webp",
        "./Assets/andhra/PENNABADIVANDLAPALLY/img (4).webp",
        "./Assets/andhra/PENNABADIVANDLAPALLY/img (5).webp",
      ],
    },
    {
      name: "Rajanalapalli",
      pdf: "./Assets/andhra/Rajanalapalli/pdf.pdf",
      profileImg: "/Assets/andhra/Obulareddypally/profile.webp",
      profileName: "Dr. Krishna Reddy Aruna Reddy",
      images: [
        "./Assets/andhra/Rajanalapalli/img (1).webp",
        "./Assets/andhra/Rajanalapalli/img (2).webp",
        "./Assets/andhra/Rajanalapalli/img (3).webp",
        "./Assets/andhra/Rajanalapalli/img (4).webp",
      ],
    },
    {
      name: "Chejerla",
      pdf: "./Assets/andhra/chejerla/pdf.pdf",
      profileImg: "/Assets/andhra/Thondavada/profile.webp",
      profileName: "Dr. Mohan Mallam",
      images: [
        "./Assets/andhra/chejerla/img (1).webp",
        "./Assets/andhra/chejerla/img (2).webp",
        "./Assets/andhra/chejerla/img (3).webp",
        "./Assets/andhra/chejerla/img (4).webp",
        "./Assets/andhra/chejerla/img (5).webp",
      ],
    },
    {
      name: "Kothapalli",
      pdf: "./Assets/andhra/kothapalli/pdf.pdf",
      profileImg: "/Assets/andhra/Obulareddypally/profile.webp",
      profileName: "Dr. Krishna Reddy Aruna Reddy",
      images: [
        "./Assets/andhra/kothapalli/img (1).webp",
        "./Assets/andhra/kothapalli/img (2).webp",
        "./Assets/andhra/kothapalli/img (3).webp",
        "./Assets/andhra/kothapalli/img (4).webp",
        "./Assets/andhra/kothapalli/img (5).webp",
      ],
    },
    {
      name: "Gudalagondhi",
      pdf: "./Assets/andhra/gudala_gondi/pdf.pdf",
      profileImg: "/Assets/andhra/Obulareddypally/profile.webp",
      profileName: "Dr. Krishna Reddy Aruna Reddy",
      images: [
        "./Assets/andhra/gudala_gondi/img (1).webp",
        "./Assets/andhra/gudala_gondi/img (2).webp",
        "./Assets/andhra/gudala_gondi/img (3).webp",
        "./Assets/andhra/gudala_gondi/img (4).webp",
        "./Assets/andhra/gudala_gondi/img (5).webp",
      ],
    },
  ],
  karnataka: [
    {
      name: "Guluru2",
      pdf: "/Assets/telenaga/Guluru2/pdf.pdf",
      profileImg: "/Assets/karnataka/Guluru2/profile.webp",
      profileName: "Dr Bhaskar Purushottam",
      images: [
        "./Assets/karnataka/Guluru2/img (1).webp",
        "./Assets/karnataka/Guluru2/img (2).webp",
        "./Assets/karnataka/Guluru2/img (3).webp",
        "./Assets/karnataka/Guluru2/img (4).webp",
      ],
    },
    {
      name: "Humchadakatte",
      pdf: "/Assets/telenaga/humchadakatte/pdf.pdf",
      profileImg: "/Assets/karnataka/humchadakatte/profile.webp",
      profileName: "Dr Manjunath Shikaripur",
      images: [
        "./Assets/karnataka/humchadakatte/img (1).webp",
        "./Assets/karnataka/humchadakatte/img (2).webp",
        "./Assets/karnataka/humchadakatte/img (3).webp",
        "./Assets/karnataka/humchadakatte/img (4).webp",
        "./Assets/karnataka/humchadakatte/img (5).webp",
      ],
    },
    {
      name: "Guluru",
      pdf: "/Assets/telenaga/Guluru/pdf.pdf",
      profileImg: "/Assets/karnataka/Guluru/profile.webp",
      profileName: "Dr Anuradha Maan",
      images: [
        "./Assets/karnataka/Guluru/img (1).webp",
        "./Assets/karnataka/Guluru/img (2).webp",
        "./Assets/karnataka/Guluru/img (3).webp",
        "./Assets/karnataka/Guluru/img (4).webp",
        "./Assets/karnataka/Guluru/img (5).webp",
      ],
    },
    {
      name: "Kesaramadu",
      pdf: "/Assets/karnataka/kesaramadu/pdf.pdf",
      profileImg: "/Assets/karnataka/kesaramadu/profile.webp",
      profileName: "Anoop & Amita Mamtani",
      images: [
        "./Assets/karnataka/kesaramadu/img (1).webp",
        "./Assets/karnataka/kesaramadu/img (2).webp",
        "./Assets/karnataka/kesaramadu/img (3).webp",
        "./Assets/karnataka/kesaramadu/img (4).webp",
        "./Assets/karnataka/kesaramadu/img (5).webp",
      ],
    },
    {
      name: "Palasandra",
      pdf: "/Assets/karnataka/palasandra/pdf.pdf",
      profileImg: "/Assets/karnataka/kesaramadu/profile.webp",
      profileName: "Anoop & Amita Mamtani",
      images: [
        "./Assets/karnataka/palasandra/img (1).webp",
        "./Assets/karnataka/palasandra/img (2).webp",
        "./Assets/karnataka/palasandra/img (3).webp",
        "./Assets/karnataka/palasandra/img (4).webp",
        "./Assets/karnataka/palasandra/img (5).webp",
      ],
    },
  ],
};
